name: TestWorkflow
on:
  workflow_dispatch:
    branches: [master]

jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Wiki
      uses: actions/checkout@v2
      with:
        repository: revarbat/BOSL2.wiki
        path: BOSL2.wiki

    - name: Apt Update
      run: sudo apt update

    - name: Install Packages
      run: sudo apt-get install -y python3-pip python3-dev python3-setuptools python3-pil

    - name: Install openscad-docsgen
      run: sudo pip3 install openscad_docsgen

    - name: Install OpenSCAD
      run: |
        cd $GITHUB_WORKSPACE
        wget https://files.openscad.org/OpenSCAD-2021.01-x86_64.AppImage
        sudo mv OpenSCAD-2021.01*-x86_64.AppImage /usr/local/bin/openscad
        sudo chmod +x /usr/local/bin/openscad
        echo "::add-matcher::.github/openscad_docsgen.json"

    - name: Make SCAD File
      run: |
        cd $GITHUB_WORKSPACE
        echo "cube(50, center=100);" > testwf.scad

    - name: TestScript
      env:
        OPENSCADPATH: $GITHUB_WORKSPACE/..
      run: |
        xvfb-run --server-args="-screen 0, 1280x720x24" -a \
        openscad -o tmp_cube.png --imgsize=640,480 --view=axes,scales --projection=o --autocenter --viewall --preview '' --hardwarnings testwf.scad

